name: Fonctionnalité
description: Proposer une amélioration
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: textarea
    id: user
    attributes:
      label: Problème utilisateur
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposition
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Critères d’acceptation
